spring:
  application:
    name: ceap-admin

  jackson:
    #  格式化返回时间 yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

server:
  servlet:
    context-path: "/ceap/admin"


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 打印sql
  global-config:
    db-config:
      logic-delete-field: isDelete  # 全局逻辑删除的字段名
      logic-delete-value: 1
      logic-not-delete-value: 0

# springdoc-openapi项目配置
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.forty
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-swagger-models: true

resilience4j:
  retry:   # 重试
    instances:
      aiBackend:
        wait-duration: 1s  # 重试等待时间
        max-attempts: 3  # 最多尝试次数

